// AUTO-GENERATED by scripts/fetch-token-data.ts — DO NOT EDIT BY HAND.
// Snapshot of the wallet's default supported chains + ERC-20 tokens, fetched once
// from the xflows API and baked in (no runtime fetch). Regenerate: bun run gen:tokens
//
//   chains: 18 (EVM only)   tokens: 39 across 15 chains

export type TokenMeta = {
  /** ERC-20 contract address, lowercased. */
  address: string;
  symbol: string;
  name: string;
  decimals: number;
  /** Remote logo URL (may be empty). */
  logo: string;
};

export type ChainMeta = {
  /** EIP-155 chain id as 0x-hex. */
  id: string;
  name: string;
  /** Native gas-token symbol. */
  symbol: string;
  rpc: string;
  decimals: number;
  color: string;
  /** Remote chain logo URL (may be empty). */
  logo: string;
};

/** Default supported EVM chains (snapshot). */
export const SUPPORTED_CHAINS: ChainMeta[] = [
  {
    "id": "0x1",
    "name": "Ethereum",
    "symbol": "ETH",
    "rpc": "https://ethereum-rpc.publicnode.com",
    "decimals": 18,
    "color": "#627EEA",
    "logo": "https://xflows.wanchain.org/Chain/Ethereum.png"
  },
  {
    "id": "0xa",
    "name": "Optimism",
    "symbol": "ETH",
    "rpc": "https://optimism-rpc.publicnode.com",
    "decimals": 18,
    "color": "#FF0420",
    "logo": "https://xflows.wanchain.org/Chain/Optimism.png"
  },
  {
    "id": "0x38",
    "name": "BNB Chain",
    "symbol": "BNB",
    "rpc": "https://bsc-rpc.publicnode.com",
    "decimals": 18,
    "color": "#F3BA2F",
    "logo": "https://xflows.wanchain.org/Chain/BNB_Chain.png"
  },
  {
    "id": "0x89",
    "name": "Polygon",
    "symbol": "MATIC",
    "rpc": "https://polygon-bor-rpc.publicnode.com",
    "decimals": 18,
    "color": "#8247E5",
    "logo": "https://xflows.wanchain.org/Chain/Polygon.png"
  },
  {
    "id": "0x92",
    "name": "Sonic",
    "symbol": "S",
    "rpc": "https://rpc.soniclabs.com",
    "decimals": 18,
    "color": "#1969FF",
    "logo": "https://xflows.wanchain.org/Chain/Sonic.webp"
  },
  {
    "id": "0xc4",
    "name": "X Layer",
    "symbol": "OKB",
    "rpc": "https://rpc.xlayer.tech",
    "decimals": 18,
    "color": "#1A1A1A",
    "logo": "https://xflows.wanchain.org/Chain/X_Layer.png"
  },
  {
    "id": "0x144",
    "name": "zkSync Era",
    "symbol": "ETH",
    "rpc": "https://mainnet.era.zksync.io",
    "decimals": 18,
    "color": "#8C8DFC",
    "logo": "https://xflows.wanchain.org/Chain/zkSync_Era.png"
  },
  {
    "id": "0x1e0",
    "name": "World Chain",
    "symbol": "WORLDETH",
    "rpc": "https://worldchain-mainnet.g.alchemy.com/public",
    "decimals": 18,
    "color": "#1A1A1A",
    "logo": "https://xflows.wanchain.org/Chain/WorldChain.webp"
  },
  {
    "id": "0x250",
    "name": "Astar",
    "symbol": "ASTR",
    "rpc": "https://evm.astar.network",
    "decimals": 18,
    "color": "#1B6DC1",
    "logo": "https://xflows.wanchain.org/Chain/Astar.png"
  },
  {
    "id": "0x378",
    "name": "Wanchain",
    "symbol": "WAN",
    "rpc": "https://gwan-ssl.wandevs.org:56891",
    "decimals": 18,
    "color": "#2A6BE9",
    "logo": "https://xflows.wanchain.org/Chain/Wanchain.png"
  },
  {
    "id": "0x440",
    "name": "Metis",
    "symbol": "METIS",
    "rpc": "https://andromeda.metis.io/?owner=1088",
    "decimals": 18,
    "color": "#00DACC",
    "logo": "https://xflows.wanchain.org/Chain/Metis.png"
  },
  {
    "id": "0x44d",
    "name": "Polygon zkEVM",
    "symbol": "ETH",
    "rpc": "https://zkevm-rpc.com",
    "decimals": 18,
    "color": "#7B3FE4",
    "logo": "https://xflows.wanchain.org/Chain/PolygonZk.webp"
  },
  {
    "id": "0x2105",
    "name": "Base",
    "symbol": "ETH",
    "rpc": "https://base-rpc.publicnode.com",
    "decimals": 18,
    "color": "#0052FF",
    "logo": "https://xflows.wanchain.org/Chain/Base.png"
  },
  {
    "id": "0xa4b1",
    "name": "Arbitrum",
    "symbol": "ETH",
    "rpc": "https://arbitrum-one-rpc.publicnode.com",
    "decimals": 18,
    "color": "#28A0F0",
    "logo": "https://xflows.wanchain.org/Chain/Arbitrum.png"
  },
  {
    "id": "0xa4ec",
    "name": "Celo",
    "symbol": "CELO",
    "rpc": "https://forno.celo.org",
    "decimals": 18,
    "color": "#FCB728",
    "logo": "https://xflows.wanchain.org/Chain/Celo.png"
  },
  {
    "id": "0xa86a",
    "name": "Avalanche C",
    "symbol": "AVAX",
    "rpc": "https://avalanche-c-chain-rpc.publicnode.com",
    "decimals": 18,
    "color": "#E84142",
    "logo": "https://xflows.wanchain.org/Chain/Avalanche_C.png"
  },
  {
    "id": "0xe708",
    "name": "Linea",
    "symbol": "ETH",
    "rpc": "https://linea-rpc.publicnode.com",
    "decimals": 18,
    "color": "#61DFFF",
    "logo": "https://xflows.wanchain.org/Chain/Linea.png"
  },
  {
    "id": "0x13e31",
    "name": "Blast",
    "symbol": "ETH",
    "rpc": "https://blast-rpc.publicnode.com",
    "decimals": 18,
    "color": "#FCD000",
    "logo": "https://xflows.wanchain.org/Chain/Blast.png"
  }
];

/** Default ERC-20 tokens per chain (0x-hex chain id -> tokens). */
export const DEFAULT_TOKENS: Record<string, TokenMeta[]> = {
  "0x1": [
    {
      "address": "0xdac17f958d2ee523a2206206994597c13d831ec7",
      "symbol": "USDT",
      "name": "Tether",
      "decimals": 6,
      "logo": "https://xflows.wanchain.org/Token/USDT.png"
    },
    {
      "address": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
      "symbol": "USDC",
      "name": "USDC",
      "decimals": 6,
      "logo": "https://xflows.wanchain.org/Token/USDC.png"
    },
    {
      "address": "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599",
      "symbol": "WBTC",
      "name": "Wrapped BTC",
      "decimals": 8,
      "logo": "https://xflows.wanchain.org/Token/WBTC.png"
    }
  ],
  "0xa": [
    {
      "address": "0x94b008aa00579c1307b0ef2c499ad98a8ce58e58",
      "symbol": "USDT",
      "name": "Tether USD",
      "decimals": 6,
      "logo": "https://xflows.wanchain.org/Token/USDT.png"
    },
    {
      "address": "0x0b2c639c533813f4aa9d7837caf62653d097ff85",
      "symbol": "USDC",
      "name": "usdc",
      "decimals": 6,
      "logo": "https://xflows.wanchain.org/Token/USDC.png"
    },
    {
      "address": "0x68f180fcce6836688e9084f035309e29bf0a2095",
      "symbol": "WBTC",
      "name": "Wrapped BTC",
      "decimals": 8,
      "logo": "https://xflows.wanchain.org/Token/WBTC.png"
    }
  ],
  "0x38": [
    {
      "address": "0x55d398326f99059ff775485246999027b3197955",
      "symbol": "USDT",
      "name": "Tether",
      "decimals": 18,
      "logo": "https://xflows.wanchain.org/Token/USDT.png"
    },
    {
      "address": "0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d",
      "symbol": "USDC",
      "name": "USD Coin",
      "decimals": 18,
      "logo": "https://xflows.wanchain.org/Token/USDC.png"
    },
    {
      "address": "0x7130d2a12b9bcbfae4f2634d864a1ee1ce3ead9c",
      "symbol": "BTCB",
      "name": "Binance-Peg BTCB Token",
      "decimals": 18,
      "logo": "https://xflows.wanchain.org/Token/BTCB.png"
    },
    {
      "address": "0x2170ed0880ac9a755fd29b2688956bd959f933f8",
      "symbol": "ETH",
      "name": "Binance-Peg Ethereum Token",
      "decimals": 18,
      "logo": "https://xflows.wanchain.org/Token/ETH.png"
    },
    {
      "address": "0x3ee2200efb3400fabb9aacf31297cbdd1d435d47",
      "symbol": "ADA",
      "name": "ADA",
      "decimals": 18,
      "logo": "https://xflows.wanchain.org/Chain/Cardano.png"
    }
  ],
  "0x89": [
    {
      "address": "0x7ceb23fd6bc0add59e62ac25578270cff1b9f619",
      "symbol": "WETH",
      "name": "Wrapped Ether",
      "decimals": 18,
      "logo": "https://xflows.wanchain.org/Token/WETH.png"
    },
    {
      "address": "0xc2132d05d31c914a87c6611c10748aeb04b58e8f",
      "symbol": "USDT",
      "name": "Tether",
      "decimals": 6,
      "logo": "https://xflows.wanchain.org/Token/USDT.png"
    },
    {
      "address": "0x3c499c542cef5e3811e1192ce70d8cc03d5c3359",
      "symbol": "USDC",
      "name": "USD Coin",
      "decimals": 6,
      "logo": "https://xflows.wanchain.org/Token/USDC.png"
    }
  ],
  "0x92": [
    {
      "address": "0x29219dd400f2bf60e5a23d13be72b486d4038894",
      "symbol": "USDC",
      "name": "USDC",
      "decimals": 6,
      "logo": "https://xflows.wanchain.org/Token/USDC.png"
    }
  ],
  "0xc4": [
    {
      "address": "0x1e4a5963abfd975d8c9021ce480b42188849d41d",
      "symbol": "USDT",
      "name": "Tether USD",
      "decimals": 6,
      "logo": "https://xflows.wanchain.org/Token/USDT.png"
    },
    {
      "address": "0x74b7f16337b8972027f6196a17a631ac6de26d22",
      "symbol": "USDC",
      "name": "USDC",
      "decimals": 6,
      "logo": "https://xflows.wanchain.org/Token/USDC.png"
    }
  ],
  "0x144": [
    {
      "address": "0x3355df6d4c9c3035724fd0e3914de96a5a83aaf4",
      "symbol": "USDC.e",
      "name": "bridged usdc",
      "decimals": 6,
      "logo": "https://xflows.wanchain.org/Token/USDC.png"
    }
  ],
  "0x1e0": [
    {
      "address": "0x79a02482a880bce3f13e09da970dc34db4cd24d1",
      "symbol": "USDC",
      "name": "USDC",
      "decimals": 6,
      "logo": "https://xflows.wanchain.org/Token/USDC.png"
    }
  ],
  "0x250": [
    {
      "address": "0xffffffff000000000000000000000001000007c0",
      "symbol": "USDT",
      "name": "Tether USD",
      "decimals": 6,
      "logo": "https://xflows.wanchain.org/Token/USDT.png"
    }
  ],
  "0x378": [
    {
      "address": "0x11e77e27af5539872efed10abaa0b408cfd9fbbd",
      "symbol": "wanUSDT",
      "name": "wanUSDT",
      "decimals": 6,
      "logo": "https://xflows.wanchain.org/Token/wanUSDT.png"
    },
    {
      "address": "0x52a9cea01c4cbdd669883e41758b8eb8e8e2b34b",
      "symbol": "wanUSDC",
      "name": "wanUSDC",
      "decimals": 6,
      "logo": "https://xflows.wanchain.org/Token/wanUSDC.png"
    },
    {
      "address": "0xe3ae74d1518a76715ab4c7bedf1af73893cd435a",
      "symbol": "wanETH",
      "name": "wanETH",
      "decimals": 18,
      "logo": "https://xflows.wanchain.org/Token/wanETH.png"
    },
    {
      "address": "0x50c439b6d602297252505a6799d84ea5928bcfb6",
      "symbol": "wanBTC",
      "name": "wanBTC",
      "decimals": 8,
      "logo": "https://xflows.wanchain.org/Token/wanBTC.png"
    },
    {
      "address": "0x2ea407aa69be7367bf231e76b51fab9ec436766c",
      "symbol": "xWAN",
      "name": "xWAN",
      "decimals": 18,
      "logo": "https://xflows.wanchain.org/Token/xWAN.svg"
    },
    {
      "address": "0x79d745178bc271a1f29f8fbe9251dfc512db842c",
      "symbol": "wanADA",
      "name": "wanADA",
      "decimals": 6,
      "logo": "https://xflows.wanchain.org/Chain/Cardano.png"
    }
  ],
  "0x440": [
    {
      "address": "0xbb06dca3ae6887fabf931640f67cab3e3a16f4dc",
      "symbol": "USDT",
      "name": "m.USDT",
      "decimals": 6,
      "logo": "https://xflows.wanchain.org/Token/USDT.png"
    },
    {
      "address": "0xea32a96608495e54156ae48931a7c20f0dcc1a21",
      "symbol": "USDC",
      "name": "m.USDC",
      "decimals": 6,
      "logo": "https://xflows.wanchain.org/Token/USDC.png"
    },
    {
      "address": "0x420000000000000000000000000000000000000a",
      "symbol": "ETH",
      "name": "WETH",
      "decimals": 18,
      "logo": "https://xflows.wanchain.org/Token/ETH.png"
    },
    {
      "address": "0x433e43047b95cb83517abd7c9978bdf7005e9938",
      "symbol": "BTC",
      "name": "m.WBTC",
      "decimals": 8,
      "logo": "https://xflows.wanchain.org/Token/WBTC.png"
    }
  ],
  "0x2105": [
    {
      "address": "0x833589fcd6edb6e08f4c7c32d4f71b54bda02913",
      "symbol": "USDC",
      "name": "usdc",
      "decimals": 6,
      "logo": "https://xflows.wanchain.org/Token/USDC.png"
    },
    {
      "address": "0x50c5725949a6f0c72e6c4a641f24049a917db0cb",
      "symbol": "DAI",
      "name": "Dai Stablecoin",
      "decimals": 18,
      "logo": "https://xflows.wanchain.org/Token/DAI.png"
    }
  ],
  "0xa4b1": [
    {
      "address": "0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9",
      "symbol": "USDT",
      "name": "tether",
      "decimals": 6,
      "logo": "https://xflows.wanchain.org/Token/USDT.png"
    },
    {
      "address": "0xaf88d065e77c8cc2239327c5edb3a432268e5831",
      "symbol": "USDC",
      "name": "usdc",
      "decimals": 6,
      "logo": "https://xflows.wanchain.org/Token/USDC.png"
    },
    {
      "address": "0x2f2a2543b76a4166549f7aab2e75bef0aefc5b0f",
      "symbol": "WBTC",
      "name": "Wrapped BTC",
      "decimals": 8,
      "logo": "https://xflows.wanchain.org/Token/WBTC.png"
    }
  ],
  "0xa4ec": [
    {
      "address": "0xceba9300f2b948710d2653dd7b07f33a8b32118c",
      "symbol": "USDC",
      "name": "USDC",
      "decimals": 6,
      "logo": "https://xflows.wanchain.org/Token/USDC.png"
    }
  ],
  "0xa86a": [
    {
      "address": "0x9702230a8ea53601f5cd2dc00fdbc13d4df4a8c7",
      "symbol": "USDT",
      "name": "Tether",
      "decimals": 6,
      "logo": "https://xflows.wanchain.org/Token/USDT.png"
    },
    {
      "address": "0xb97ef9ef8734c71904d8002f8b6bc66dd9c48a6e",
      "symbol": "USDC",
      "name": "USDC",
      "decimals": 6,
      "logo": "https://xflows.wanchain.org/Token/USDC.png"
    },
    {
      "address": "0x152b9d0fdc40c096757f570a51e494bd4b943e50",
      "symbol": "WBTC",
      "name": "Wrapped BTC",
      "decimals": 8,
      "logo": "https://xflows.wanchain.org/Token/WBTC.png"
    }
  ]
};
