// CI lint: Windows shows the .ico exactly as shipped — nothing rounds it for us
// (unlike the impression macOS gives, where the .icns was authored pre-rounded).
// Assert every image inside src-tauri/icons/icon.ico has its rounded corners
// baked in: the four corner pixels must be fully transparent.
//
// Run: bun scripts/check-icons.ts
// Exit code 1 lists every offending entry.

import { PNG } from 'pngjs';
import { join } from 'node:path';

const ICO_PATH = join(import.meta.dir, '..', 'src-tauri', 'icons', 'icon.ico');

interface IcoEntry {
  width: number;
  height: number;
  offset: number;
  size: number;
}

function parseIcoDirectory(buf: Buffer): IcoEntry[] {
  if (buf.readUInt16LE(0) !== 0 || buf.readUInt16LE(2) !== 1) {
    throw new Error(`${ICO_PATH}: not an ICO file (bad ICONDIR header)`);
  }
  const count = buf.readUInt16LE(4);
  const entries: IcoEntry[] = [];
  for (let i = 0; i < count; i++) {
    const base = 6 + i * 16;
    entries.push({
      // 0 in the directory means 256
      width: buf.readUInt8(base) || 256,
      height: buf.readUInt8(base + 1) || 256,
      size: buf.readUInt32LE(base + 8),
      offset: buf.readUInt32LE(base + 12),
    });
  }
  return entries;
}

const PNG_MAGIC = Buffer.from([0x89, 0x50, 0x4e, 0x47]);

function decodeEntry(buf: Buffer, entry: IcoEntry): PNG {
  const data = buf.subarray(entry.offset, entry.offset + entry.size);
  if (!data.subarray(0, 4).equals(PNG_MAGIC)) {
    // tauri-icon writes PNG-compressed entries; a BMP entry means the file was
    // regenerated by a different tool. Treat as a failure so it gets looked at.
    throw new Error(
      `entry ${entry.width}x${entry.height} is not PNG-compressed; regenerate the ico with scripts/make-windows-icon.ts`,
    );
  }
  return PNG.sync.read(Buffer.from(data));
}

function cornerAlphas(png: PNG): { name: string; alpha: number }[] {
  const { width: w, height: h, data } = png;
  const alphaAt = (x: number, y: number) => data[(y * w + x) * 4 + 3];
  return [
    { name: 'top-left', alpha: alphaAt(0, 0) },
    { name: 'top-right', alpha: alphaAt(w - 1, 0) },
    { name: 'bottom-left', alpha: alphaAt(0, h - 1) },
    { name: 'bottom-right', alpha: alphaAt(w - 1, h - 1) },
  ];
}

const ico = Buffer.from(await Bun.file(ICO_PATH).arrayBuffer());
const entries = parseIcoDirectory(ico);
if (entries.length === 0) {
  console.error(`${ICO_PATH}: ICO contains no images`);
  process.exit(1);
}

let failed = false;
for (const entry of entries) {
  let png: PNG;
  try {
    png = decodeEntry(ico, entry);
  } catch (e) {
    console.error(`FAIL  ${(e as Error).message}`);
    failed = true;
    continue;
  }
  const opaque = cornerAlphas(png).filter((c) => c.alpha !== 0);
  if (opaque.length > 0) {
    const detail = opaque.map((c) => `${c.name}=${c.alpha}`).join(', ');
    console.error(
      `FAIL  ${png.width}x${png.height}: opaque corner pixels (${detail}) — rounded corners are not baked in`,
    );
    failed = true;
  } else {
    console.log(`ok    ${png.width}x${png.height}: corners transparent`);
  }
}

if (failed) {
  console.error(
    '\nicon.ico will render with square corners on Windows (taskbar/desktop/installer).',
  );
  console.error('Fix: bun scripts/make-windows-icon.ts  (requires ImageMagick)');
  process.exit(1);
}
console.log('icon.ico: all entries have rounded corners baked in');
